version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=password

volumes:
  pg_volume:

networks:
  default:
    name: pg_network
